version: 1.0.{build}
image:
- Ubuntu
- Previous Visual Studio 2017
build_script:
- cmd: ./gradlew build
test_script:
- cmd: ./gradlew test
notifications:
- provider: Email
  to:
  - k.veneetreddy@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true