version: 1.0.{build}
image:
- Previous Visual Studio 2017

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

notifications:
- provider: Email
  to:
  - k.veneetreddy@gmail.com
  on_build_failure: true
